# MinIO - Development Environment

mode: standalone

replicas: 1

persistence:
  enabled: true
  size: 50Gi
  storageClass: "standard"

resources:
  requests:
    memory: 512Mi
    cpu: 250m
  limits:
    memory: 2Gi
    cpu: 1000m

existingSecret: "vision-minio-credentials"

buckets:
  - name: vision-images-dev
    policy: none
    purge: false

consoleService:
  type: ClusterIP

service:
  type: ClusterIP

ingress:
  enabled: false

metrics:
  serviceMonitor:
    enabled: true
