# Redis - Production Environment

architecture: replication

auth:
  enabled: true
  existingSecret: "vision-redis-credentials"
  existingSecretPasswordKey: "password"

master:
  persistence:
    enabled: true
    size: 20Gi
    storageClass: "premium-rwo"
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 250m
      memory: 512Mi
  podAntiAffinity:
    enabled: true

replica:
  replicaCount: 2
  persistence:
    enabled: true
    size: 20Gi
    storageClass: "premium-rwo"
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 250m
      memory: 512Mi

sentinel:
  enabled: true
  quorum: 2

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 15s

networkPolicy:
  enabled: true

podDisruptionBudget:
  enabled: true
  minAvailable: 1
