# Redis - Development Environment

architecture: standalone

auth:
  enabled: true
  existingSecret: "vision-redis-credentials"
  existingSecretPasswordKey: "password"

master:
  persistence:
    enabled: true
    size: 8Gi
    storageClass: "standard"
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi

metrics:
  enabled: true
  serviceMonitor:
    enabled: true

networkPolicy:
  enabled: true
