apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vision-api.fullname" . }}-config
  labels:
    {{- include "vision-api.labels" . | nindent 4 }}
data:
  LOG_LEVEL: {{ .Values.logLevel | default "INFO" | quote }}
  MINIO_BUCKET: {{ .Values.minioBucket | default "vision-images" | quote }}
