# PostgreSQL Base Configuration (Optional)

auth:
  username: postgres
  password: postgres
  database: visiondb

primary:
  persistence:
    enabled: false
  
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
